# Simulation

## $latex \phi = (-1, 1)^T$

### Parameters

```{r params-misq1, echo=FALSE}
source("pre.R")
show.source("misq1.params.R")
```

### $latex D = 0$

- $latex S_1(t)$ is $latex N(0,1)$ distributed.
- $latex S_2(t)$ is $latex N(0,1)$ distributed.

```{r qqnorm-misq1-1, echo=FALSE}
source("pre.R")
load("misq1-1.Rdata")
test.normality(sim.data)
```

### $latex D = 1$

- $latex S_1(t)$ is $latex N(0,1)$ distributed.
- $latex S_2(t)$ is $latex N(1,1)$ distributed.

```{r qqnorm-misq1-2, echo=FALSE}
source("pre.R")
load("misq1-2.Rdata")
test.normality(sim.data)
```


### $latex D = 10$

- $latex S_1(t)$ is $latex N(0,1)$ distributed.
- $latex S_2(t)$ is $latex N(1,1)$ distributed.

```{r qqnorm-misq1-3, echo=FALSE}
source("pre.R")
load("misq1-3.Rdata")
test.normality(sim.data)
```


### $latex D = 100$

- $latex S_1(t)$ is $latex N(0,1)$ distributed.
- $latex S_2(t)$ is $latex N(1,1)$ distributed.

```{r qqnorm-misq1-4, echo=FALSE}
source("pre.R")
load("misq1-4.Rdata")
test.normality(sim.data)
```